config/routes.rb
BlackSwan::Application.routes.draw do
  match "/transactions/m", :to => "transactions#mobile", :via => :get
  resources :transactions
  match "/transactions/transfer", :to => "transactions#transfer", :via => :post
  resources :accounts do 
    resources :transactions
  end
  resources :category do
    resources :transactions
  end
  get "/reports/:date" => "reports#show"
  get "/reports/" => "reports#index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#landing"
  devise_for :users
  resources :users
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!
  # GET /transactions
  # GET /transactions.json
  def index
    #valid_account_ids = current_user.accounts.map{|a|a.id}
    if params[:account_id]
      @account = current_user.accounts.find(params[:account_id])
    elsif params[:category_id]
      @category = Category.find(params[:category_id])
    else
      @account = current_user.accounts.current_accounts.first
    end

    if @account
      @transactions = Transaction.where(:account_id => @account.id).order("date desc, created_at desc").limit(100)
      @transaction = Transaction.new(:date => Date.today, :account_id => @account.id)
    else
      @transactions = Transaction.where(:category_id => @category.id).order("date desc, created_at desc").limit(100)
    end

    @current_date = Date.today

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @transaction.date = Date.today

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to account_transactions_path(@transaction.account), notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { redirect_to account_transactions_path(current_user.accounts.expense_accounts.first), alert: 'Transaction could not be added.' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def mobile
    render :layout => 'mobile'
  end

  def transfer
    from_account = current_user.accounts.find_by_id(params[:debit_from_id])
    to_account = current_user.accounts.find_by_id(params[:credit_to_id])
    amount = params[:amount].to_i if params[:amount]
    date = params[:on].to_date if params[:on]
    category = Category.find_by_name('transfer')

    if amount > 0 and date
      t1 = Transaction.create(:amount => amount, :t_type => Transaction::TYPE_DEBIT, :account_id => from_account.id, :category_id => category.id, :description => "Transferring to #{to_account.name}", :date => date)
      t2 = Transaction.create(:amount => amount, :t_type => Transaction::TYPE_CREDIT, :account_id => to_account.id, :category_id => category.id, :description => "Transferred from #{from_account.name}", :date => date)
    end

    redirect_to account_transactions_path(to_account)
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        @transaction.account.update_transactions
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_category_sidebar.html.erb
<div class="span3">
  <div class="widget widget-table">
    <div class="widget-header">
      <h3>Categories</h3>
    </div>

    <div class="widget-content">
 
      <ul class="nav nav-list">
        <li class="nav-header">Income</li>
        <%- Category.income_categories.each do |c| %>
          <li class="<%= 'active' if @category == c %>"><%= link_to(c.name,category_transactions_path(c)) %></li>
          <%- c.categories.each do |cc| %>
            <li class="<%= 'active' if @category == cc %>"><%= link_to(cc.name,category_transactions_path(cc),:class => "indent") %></li>
          <%- end -%>
        <%- end -%>
        <li class="nav-header">Expense</li>
        <%- Category.expense_categories.each do |c| %>
          <li class="<%= 'active' if @category == c %>"><%= link_to(c.name,category_transactions_path(c)) %></li>
          <%- c.categories.each do |cc| %>
            <li class="<%= 'active' if @category == cc %>"><%= link_to(cc.name,category_transactions_path(cc),:class => "indent") %></li>
          <%- end -%>
        <%- end -%>
      </ul>
    </div>
  </div>
</div>

app/views/transactions/_expense.html.erb
<div id="new-expense" class="modal" style="display:none;">
  <%- transaction.t_type = Transaction::TYPE_DEBIT -%>
  <%= form_for(transaction, {:html => {:class => "form-inline"}}) do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Expense</h3>
    </div>
    <div class="modal-body">
      <%= f.text_field :date , :class => "calendar input-small", 'data-date' => Date.today.strftime("%d-%m-%Y"), 'data-date-format' => "dd-mm-yyyy", :placeholder => "Date"%>
      <div class="input-prepend">
        <span class="add-on">Rs.</span>
        <%= f.text_field :amount, :placeholder => "Amount" , :class => "input-small"%>
      </div>
      <%= f.select :account_id, ["-- From --"] + Account.all.collect{|p| [p.name, p.id]}, {}, { :class => "input-small"} %>
      <%= f.hidden_field :t_type%>
      <%= f.select :category_id, ["-- Type --"] + expense_category_options, {}, {:class => "input-small"}%>
      <%# f.select :category_id, ["-- Type --"] + Category.expense_categories.collect{|p| [p.name.titleize, p.id]} , {}, {:class => "input-small"}%>
      <%= f.text_field :description, :placeholder => "Description" %>
    </div>

    <div class="modal-footer">
      <%= f.button :submit, :class => "btn btn-info" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/transactions/_form.html.erb
<div id="new-transaction" class="modal" style="display:none;">
  <%= simple_form_for(@transaction) do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Transaction</h3>
    </div>
    <div class="modal-body">
      <%= f.error_notification %>

      <%= f.input :amount %>
      <%= f.association :debit_from %>
      <%= f.association :credit_to %>
      <%= f.association :category %>
      <%= f.input :description %>
      <%= f.input :duration %>
      <%= f.input :on %>
    </div>

    <div class="modal-footer">
      <%= f.button :submit, :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/transactions/_income.html.erb
<div id="new-income" class="modal" style="display:none;">
  <%- transaction.t_type = Transaction::TYPE_CREDIT -%>
  <%= form_for(transaction, {:html => {:class => "form-inline"}}) do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Income</h3>
    </div>
    <div class="modal-body">
      <%= f.text_field :date , :class => "calendar input-small", 'data-date' => Date.today.strftime("%d-%m-%Y"), 'data-date-format' => "dd-mm-yyyy", :placeholder => "Date"%>
      <div class="input-prepend">
        <span class="add-on">Rs.</span>
        <%= f.text_field :amount, :placeholder => "Amount" , :class => "input-small"%>
      </div>
      <%= f.select :account_id, ["-- To --"] + Account.all.collect{|p| [p.name, p.id]}, {}, { :class => "input-small"} %>
      <%= f.hidden_field :t_type%>
      <%= f.select :category_id, ["-- Type --"] + Category.income_categories.collect{|p| [p.name.titleize, p.id]} , {}, {:class => "input-small"}%>
      <%= f.text_field :description, :placeholder => "Description" %>
    </div>

    <div class="modal-footer">
      <%= f.button :submit, :class => "btn btn-info" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/transactions/_new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/_transaction_sidebar.html.erb
<div class="span3">
  <div class="widget widget-table">
    <div class="widget-header">
      <div class="btn-group">
        <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
          <%= @account.name %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <% current_user.accounts.all.each do |a| %>
            <%- next if @account == a -%>
            <li><%=link_to(a.name,account_transactions_path(a)) %></li>
          <%- end -%>
        </ul>
      </div>
    </div>

    <div class="widget-content">
 
      <br/>
      <div class="add-transaction-container">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#add-expense" data-toggle="tab">Expense</a></li>
          <li><a href="#add-income" data-toggle="tab">Income</a></li>
          <li><a href="#add-transfer" data-toggle="tab">Transfer</a></li>
        </ul>

        <div class="tab-content" style="background-color:white;">
          <div class="tab-pane active" id="add-expense">
            <h3>Add Expense</h3>
            <%- @transaction.t_type = Transaction::TYPE_DEBIT -%>
            <%= form_for(@transaction, {:html => {:class => "form-horizontal side-form"}}) do |f| %>
              <div class="control-group">
                <%= f.label :date, "Date", :class => "control-label" %>
                <div class="controls">
                  <!--
                  <div class="input-append date calendar" data-date="<%= @transaction.date.strftime("%d-%m-%Y") %>" data-date-format="dd-mm-yyyy">
                    <input class="calendar input-small" id="transaction_date" name="transaction[date]" type="text" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" readonly>
                    <span class="add-on"><i class="icon-calendar"></i></span>
                  </div>
                  -->
                  <input class="input-small" id="transaction_date" name="transaction[date]" type="date" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" >
                </div>
              </div>

              <div class="control-group">
                <%= f.label :amount, "Amount", :class => "control-label" %>
                <div class="controls">
                  <div class="input-prepend">
                    <span class="add-on">&#8377;</span>
                    <%= f.text_field :amount, :placeholder => "Amount" , :class => "input-small"%>
                  </div>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :account_id, "Account", :class => "control-label" %>
                <div class="controls">
                  <%= f.select :account_id, ["-- From --"] + current_user.accounts.expense_accounts.collect{|p| [p.name, p.id]}, {}, { :class => "input-small"} %>
                  <%= f.hidden_field :t_type%>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :category_id, "Category", :class => "control-label" %>
                <div class="controls">
                  <%= f.select :category_id, ["-- Type --"] + expense_category_options, {}, {:class => "input-small"}%>
                </div>
              </div>

              <%= f.text_field :description, :placeholder => "Description" %>

              <div class="form-actions">
                <%= f.button :submit, :class => "btn btn-info" %>
              </div>
            <% end %>

          </div>


          <div class="tab-pane" id="add-income">
            <h3>Add Income</h3>
            <%- @transaction.t_type = Transaction::TYPE_CREDIT -%>
            <%= form_for(@transaction, {:html => {:class => "form-horizontal side-form"}}) do |f| %>
              <div class="control-group">
                <%= f.label :date, "Date", :class => "control-label" %>
                <div class="controls">
                  <div class="input-append date calendar" data-date="<%= @transaction.date.strftime("%d-%m-%Y") %>" data-date-format="dd-mm-yyyy">
                    <input class="calendar input-small" id="transaction_date" name="transaction[date]" type="text" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" readonly>
                    <span class="add-on"><i class="icon-calendar"></i></span>
                  </div>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :amount, "Amount", :class => "control-label" %>
                <div class="controls">
                  <div class="input-prepend">
                    <span class="add-on">&#8377;</span>
                    <%= f.text_field :amount, :placeholder => "Amount" , :class => "input-small"%>
                  </div>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :account_id, "Account", :class => "control-label" %>
                <div class="controls">
                  <%= f.select :account_id, ["-- To --"] + current_user.accounts.all.collect{|p| [p.name, p.id]}, {}, { :class => "input-small"} %>
                  <%= f.hidden_field :t_type%>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :category_id, "Category", :class => "control-label" %>
                <div class="controls">
                  <%= f.select :category_id, ["-- Type --"] + Category.income_categories.collect{|p| [p.name.titleize, p.id]} , {}, {:class => "input-small"}%>
                </div>
              </div>

              <%= f.text_field :description, :placeholder => "Description" %>

              <div class="form-actions">
                <%= f.button :submit, :class => "btn btn-info" %>
              </div>
            <% end %>

          </div>


          <div class="tab-pane" id="add-transfer">
            <h3>Transfer Funds</h3>
            <%= form_for(@transaction, {:url => transactions_transfer_path, :html => {:class => "form-horizontal side-form"}}) do |f| %>
              <div class="control-group">
                <%= label_tag :on, "Date", :class => "control-label" %>
                <div class="controls">
                  <div class="input-append date calendar" data-date="<%= Date.today.strftime("%d-%m-%Y") %>" data-date-format="dd-mm-yyyy">
                    <input class="calendar input-small" id="on" name="on" type="text" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" readonly>
                    <span class="add-on"><i class="icon-calendar"></i></span>
                  </div>
                </div>
              </div>

              <div class="control-group">
                <%= label_tag :amount, "Amount", :class => "control-label" %>
                <div class="controls">
                  <div class="input-prepend">
                    <span class="add-on">&#8377;</span>
                    <%= text_field_tag :amount, "", :placeholder => "Amount" , :class => "input-small"%>
                  </div>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :debit_from_id, "Debit From", :class => "control-label" %>
                <div class="controls">
                  <%= raw select_tag 'debit_from_id', options_from_collection_for_select(current_user.accounts.all, "id", "name"), {:prompt => "-- From --",:class => "input-small"} %>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :credit_to_id, "Credit To", :class => "control-label" %>
                <div class="controls">
                  <%= raw select_tag 'credit_to_id', options_from_collection_for_select(current_user.accounts.all, "id", "name"), {:prompt => "-- To --",:class => "input-small"} %>
                </div>
              </div>

              <div class="form-actions">
                <%= f.button :submit, :class => "btn btn-info" %>
              </div>
            <% end %>


          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/_transfer.html.erb
<div id="new-transfer" class="modal" style="display:none;">
  <%= form_for(transaction, {:url => transactions_transfer_path, :html => {:class => "form-inline"}}) do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Transfer</h3>
    </div>
    <div class="modal-body">
      <%= raw select_tag 'debit_from_id', options_from_collection_for_select(Account.all, "id", "name"), {:prompt => "-- From --",:class => "input-small"} %>
      <%= select_tag :credit_to_id, options_from_collection_for_select(Account.all, "id", "name"), {:prompt => "-- To --",:class => "input-small"}%>
      <div class="input-prepend">
        <span class="add-on">Rs.</span>
        <%= text_field_tag :amount, "", :placeholder => "Amount" , :class => "input-small"%>
      </div>
      <%= text_field_tag :on , "", :class => "calendar input-small", 'data-date' => Date.today.strftime("%d-%m-%Y"), 'data-date-format' => "dd-mm-yyyy", :placeholder => "Date"%>
    </div>

    <div class="modal-footer">
      <%= f.button :submit, :class => "btn btn-info" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>
<%= simple_form_for(@transaction, :html => {:class => "form-horizontal"}) do |f| %>
    <div>
      <%= f.error_notification %>
      <div class="control-group">
        <%= f.label :date, "Date", :class => "control-label" %>
        <div class="controls">
          <div class="input-append date calendar" data-date="<%= @transaction.date.strftime("%d-%m-%Y") %>" data-date-format="dd-mm-yyyy">
            <input class="calendar input-small" id="transaction_date" name="transaction[date]" type="text" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" readonly>
            <span class="add-on"><i class="icon-calendar"></i></span>
          </div>
        </div>
      </div>


      <%= f.input :amount %>
      <%= f.association :account %>
      <%= f.input :category do %>
        <%= f.select :category_id, (@transaction.t_type == Transaction::TYPE_DEBIT) ? expense_category_options : income_categories %>
      <% end %>
      <%= f.input :description %>
    </div>

      <%= f.button :submit, :class => "btn" %>
  <% end %>
</div>

app/views/transactions/index.html.erb
<%- if @account -%>
  <%= render :partial => 'transaction_sidebar' %>
<%- else -%>
  <%= render :partial => 'category_sidebar' %>
<%- end -%>

<div class="span9">
  <div class="widget widget-table action-table">
    <div class="widget-header">
          <i class="icon-money"></i>
          <h3>Transactions in <%= @account.nil? ? @category.name : @account.name %></h3>
    </div>
    <div id="transactions" class="widget-content">
      <table class="table table-bordered table-stripped">
        <thead>
          <th>Date</th>
          <th>Description</th>
          <th>Category</th>
          <th>Sub Category</th>
          <th>Type</th>
          <th>Amount</th>
          <th>Balance</th>
          <th></th>
        </tr>

        <%- tc = Category.find_by_name('transfer') -%>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%=l transaction.date %></td>
            <td><%= transaction.description %></td>
            <td><%= transaction.category.category.nil? ? transaction.category.name : transaction.category.category.name %></td>
            <td><%= transaction.category.name %></td>
            <td>
              <%- if transaction.t_type == Transaction::TYPE_CREDIT %>
                <span class="label label-success">Credit</label>
              <%- else -%>
                <span class="label label-warning">Debit</label>
              <%- end -%>
            </td>
            <td><%=rs transaction.amount %></td>
            <td><%=rs transaction.balance %></td>
            <td><%= link_to raw('<i class="icon-edit"></i>'),edit_transaction_path(transaction) if transaction.category != tc%></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/transactions/mobile.html.erb
<h1>Add Transaction</h1>

app/views/transactions/new.html.erb
<div class="segmented-control">
  <a class="control-item active" href="#item1mobile">
    Expense
  </a>
  <a class="control-item" href="#item2mobile">
    Income
  </a>
  <a class="control-item" href="#item3mobile">
    Transfer
  </a>
</div>
<div class="card">
  <div id="item1mobile" class="control-content active content-padded">
    <h3>Add Expense</h3>
    <%- @transaction.t_type = Transaction::TYPE_DEBIT -%>
    <%= form_for(@transaction, {:html => {:class => "input-group"}}) do |f| %>
      <div class="input-row">
        <%= f.label :date, "Date", :class => "control-label" %>
          <!--
          <div class="input-append date calendar" data-date="<%= @transaction.date.strftime("%d-%m-%Y") %>" data-date-format="dd-mm-yyyy">
            <input class="calendar input-small" id="transaction_date" name="transaction[date]" type="text" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" readonly>
            <span class="add-on"><i class="icon-calendar"></i></span>
          </div>
          <input class="input-small" id="transaction_date" name="transaction[date]" type="date" value="<%= @transaction.date.strftime("%d-%m-%Y") %>" >
          -->
          <%= f.date_select :date,{},:class => "date" %>
      </div>

      <div class="input-row">
        <%= f.label :amount, "Amount", :class => "control-label" %>
        <%= f.text_field :amount, :placeholder => "Amount" , :class => "input-small"%>
      </div>

      <div class="input-row">
        <%= f.label :account_id, "Account", :class => "control-label" %>
        <%= f.select :account_id, ["-- From --"] + current_user.accounts.expense_accounts.collect{|p| [p.name, p.id]}, {}, { :class => "input-small"} %>
        <%= f.hidden_field :t_type%>
      </div>

      <div class="input-row">
        <%= f.label :category_id, "Category", :class => "control-label" %>
        <%= f.select :category_id, ["-- Type --"] + expense_category_options, {}, {:class => "input-small"}%>
      </div>

      <%= f.text_field :description, :placeholder => "Description" %>

      <div class="form-actions">
        <%= f.button :submit, :class => "btn btn-positive btn-block" %>
      </div>
    <% end %>


  </div>
  <span id="item2mobile" class="control-content">Item 2</span>
  <span id="item3mobile" class="control-content">Item 3</span>
</div>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>

<p>
  <b>Debit from:</b>
  <%= @transaction.debit_from %>
</p>

<p>
  <b>Credit to:</b>
  <%= @transaction.credit_to %>
</p>

<p>
  <b>Category:</b>
  <%= @transaction.category %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>Duration:</b>
  <%= @transaction.duration %>
</p>

<p>
  <b>On:</b>
  <%= @transaction.on %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>