config/routes.rb
BlackSwan::Application.routes.draw do
  match "/transactions/m", :to => "transactions#mobile", :via => :get
  resources :transactions
  match "/transactions/transfer", :to => "transactions#transfer", :via => :post
  resources :accounts do 
    resources :transactions
  end
  resources :category do
    resources :transactions
  end
  get "/reports/:date" => "reports#show"
  get "/reports/" => "reports#index"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#landing"
  devise_for :users
  resources :users
end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :balance, :branch, :name, :number, :ac_type
  validates_presence_of :name, :branch, :number
  scope :saving_accounts, where(["ac_type = 'savings' or ac_type = 'current'"])
  scope :debt_accounts, where(["ac_type = 'credit-card' or ac_type = 'loan'"])
  scope :investment_accounts, where(["ac_type = 'investment'"])
  scope :current_accounts, where(["ac_type = 'current'"])
  scope :expense_accounts, where(["ac_type = 'savings' or ac_type = 'current' or ac_type = 'credit-card'"])

  has_and_belongs_to_many :users
  has_many :transactions, :order => "date, created_at"

  def self.savings_balance(user,on = nil)
    balance = 0
    user.accounts.saving_accounts.each do |account| 
      balance += account.closing_balance(on)
    end
    return balance
  end

  def closing_balance(on = nil)
    on = Date.today unless on
    if self.transactions.count > 0
      t = Transaction.all(:conditions => ["account_id = ? and date <= ?",self.id,on],
                          :limit => 1,
                          :order => "date desc, created_at desc").first
    end

    t.nil? ? self.balance : t.balance
  end

  def update_transactions(from_t = nil)

    if from_t
      t_index = self.transactions.index(from_t)
      return false if t_index.nil?
    else
      t_index = 0
    end

    if t_index == 0
      last_balance = self.balance
    else
      last_balance = self.transactions[t_index-1].balance
    end

    t_index.upto(self.transactions.length-1) do |i|
      t = self.transactions[i]
      if t.t_type == Transaction::TYPE_CREDIT
        t.balance = last_balance + t.amount
      else
        t.balance = last_balance - t.amount
      end
      last_balance = t.balance
      t.save
    end
  end

  def self.pretty(a)
    a = a.to_s
    if a.length <= 3
      return a
    else
      numbers = [a.slice!(-3..-1)]
      while(a.length > 2)
        numbers.insert(0,a.slice!(-2..-1))
      end
      if a.length != 0
        numbers.insert(0,a)
      end
      return numbers.join(",")
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = current_user.accounts.all

    @saving_accounts = current_user.accounts.saving_accounts
    @debt_accounts = current_user.accounts.debt_accounts
    @investment_accounts = current_user.accounts.investment_accounts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = current_user.accounts.find(params[:id])
    @transactions = @account.transactions.reverse
    @transaction = Transaction.new

    respond_to do |format|
      format.html { render "transactions/index" }
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = current_user.accounts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = current_user.accounts.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = current_user.accounts.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = current_user.accounts.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = current_user.accounts.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<tr>
  <td><%= link_to(account.name,account) %></td>
  <td><%= account.number %></td>
  <td><%= account.branch %></td>
  <td><%= account.ac_type %></td>
  <td><%= rs account.closing_balance %></td>
</tr>

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :number %>
    <%= f.input :branch %>
    <%= f.input :balance %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="card">
  <ul class="table-view">

    <li class="table-view-cell table-view-divider">Savings Account</li>

    <%- balance = 0 %>
    <%- @saving_accounts.each do |account| -%>
      <%- balance += account.closing_balance -%>
      <li class="table-view-cell">
      <a class="navigate-right" href="/accounts/<%=account.id%>/transactions" data-ignore="push">
        <span class="badge <%= (account.closing_balance > 0) ? 'badge-positive' : 'badge-negative'%>"><%= rs account.closing_balance %></span>
        <%= account.name %>
      </a>
      </li>
    <%- end -%>

    <li class="table-view-cell table-view-divider">
    <span class="badge <%= (balance > 0) ? 'badge-positive' : 'badge-negative'%>"><%= rs balance %></span>
    Total
    </li>

  </ul>
</div>

<div class="card">
  <ul class="table-view">

    <li class="table-view-cell table-view-divider">Debt Account</li>

    <%- @debt_accounts.each do |account| -%>
      <%- balance += account.closing_balance -%>
      <li class="table-view-cell">
      <a class="navigate-right" href="/accounts/<%=account.id%>/transactions" data-ignore="push">
        <span class="badge <%= (account.closing_balance > 0) ? 'badge-positive' : 'badge-negative'%>"><%= rs account.closing_balance %></span>
        <%= account.name %>
      </a>
      </li>
    <%- end -%>

    <li class="table-view-cell table-view-divider">
    <span class="badge <%= (balance > 0) ? 'badge-positive' : 'badge-negative'%>"><%= rs balance %></span>
    Total
    </li>

  </ul>
</div>


<div class="card">
  <ul class="table-view">

    <li class="table-view-cell table-view-divider">Investment Account</li>

    <%- @investment_accounts.each do |account| -%>
      <%- balance += account.closing_balance -%>
      <li class="table-view-cell">
      <a class="navigate-right" href="/accounts/<%=account.id%>/transactions" data-ignore="push">
        <span class="badge <%= (account.closing_balance > 0) ? 'badge-positive' : 'badge-negative'%>"><%= rs account.closing_balance %></span>
        <%= account.name %>
      </a>
      </li>
    <%- end -%>

    <li class="table-view-cell table-view-divider">
    <span class="badge <%= (balance > 0) ? 'badge-positive' : 'badge-negative'%>"><%= rs balance %></span>
    Total
    </li>

  </ul>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>